- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Delete application directory
  ansible.builtin.file:
    name: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    name: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip"
    dest: /app
    remote_src: yes


# echo -e "\e[36m >>>>>>>>>>>>>>>>>> Create user service <<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
# cp ${component}.service /etc/systemd/system/${component}.service &>> ${log}
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>>> Create user for roboshop <<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
# id roboshop &>> ${log}
# if [ $? -ne 0 ]; then
# useradd roboshop &>> ${log}
# fi
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>>> delete app directory <<<<<<<<<<<\e[0m" | tee -a ${log}
# rm -rf /app &>> ${log}
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>>> Create application directory <<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
# mkdir /app &>> ${log}
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>>> Download application content <<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
# curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>> ${log}
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>>> Change directory to app <<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
# cd /app &>> ${log}
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>>> Extract the application content <<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
# unzip /tmp/${component}.zip &>> ${log}
# func_exit_status