- name: install maven
  ansible.builtin.yum:
    name: maven
    state: installed
    enabled: yes

- name: app pre-requisies
  ansible.builtin.import_tasks: app-pre-req.yml

- name: build the package
  ansible.builtin.shell: mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: schema-setup
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined

- name: systemD-setup
  ansible.builtin.import_tasks: systemd-setup.yml


# echo -e "\e[36m >>>>>>>>>>>>>>>>Install maven<<<<<<<<<<<\e[0m" | tee -a ${log}
# yum install maven -y &>> ${log}
# func_exit_status

# func_prereq

# echo -e "\e[36m >>>>>>>>>>>>>>>>Build the package<<<<<<<<<<<\e[0m" | tee -a ${log}
# mvn clean package &>> ${log}
# mv target/${component}-1.0.jar ${component}.jar &>> ${log}
# func_exit_status

# echo -e "\e[36m >>>>>>>>>>>>>>>>Daemon Reload<<<<<<<<<<<\e[0m" | tee -a ${log}
# systemctl daemon-reload &>> ${log}
# func_exit_status

# func_schema_setup

# func_systemd