- name: copy mongo-repofile
  ansible.builtin.copy:
    src: mongo-repofile
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load the schema
  ansible.builtin.shell: mongo --host mongodb-dev.devops746.online </app/schema/{{component}}.js





















































